package com.pdfdancer.client.rest.fixtures;

import org.apache.pdfbox.cos.COSArray;
import org.apache.pdfbox.cos.COSString;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDDocumentInformation;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDFont;
import org.apache.pdfbox.pdmodel.font.PDType0Font;

import java.awt.Color;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Reproducibly describes the source PDF used by {@code SyntheticTextReplacementE2ETest}.
 * The end-to-end test intentionally reads the committed fixture instead of regenerating it.
 */
public final class SyntheticTextReplacementFixtureGenerator {
    private static final Path FIXTURE_ROOT = Path.of("src/test/resources/fixtures");
    private static final Path DEFAULT_OUTPUT = FIXTURE_ROOT.resolve(
            "synthetic-text/SyntheticTextReplacement.pdf");

    private SyntheticTextReplacementFixtureGenerator() {
    }

    public static void main(String[] args) throws IOException {
        Path output = args.length == 0 ? DEFAULT_OUTPUT : Path.of(args[0]);
        Files.createDirectories(output.toAbsolutePath().getParent());
        generate(output);
        System.out.println("Generated synthetic text-replacement fixture: " + output.toAbsolutePath());
    }

    static void generate(Path output) throws IOException {
        try (PDDocument document = new PDDocument()) {
            PDDocumentInformation information = document.getDocumentInformation();
            information.setTitle("Synthetic Text Replacement Fixture");
            information.setAuthor("PDFDancer Java Client Tests");
            information.setSubject("Customer-independent text and image placeholder fixture");

            PDFont roboto = loadFont(document, "Roboto-Regular.ttf");
            PDFont sourceSans = loadFont(document, "SourceSans3-Regular.ttf");
            PDFont jetBrainsMono = loadFont(document, "JetBrainsMono-Regular.ttf");
            PDFont dancingScript = loadFont(document, "DancingScript-Regular.ttf");

            PDPage page = new PDPage(PDRectangle.LETTER);
            document.addPage(page);
            try (PDPageContentStream content = new PDPageContentStream(document, page)) {
                drawText(content, roboto, 21, 64, 742,
                        "Synthetic Text Replacement Fixture", new Color(28, 43, 58));
                drawText(content, roboto, 10, 64, 721,
                        "Deterministic placeholders for text layout, font preservation, and image replacement.",
                        new Color(82, 96, 109));

                drawPlaceholder(content, roboto, 13, 670,
                        "{{organization_name}} employee");
                drawPlaceholder(content, sourceSans, 12, 568,
                        "{{organization_name}} members use the synthetic program");
                drawPlaceholder(content, jetBrainsMono, 12, 466,
                        "{{support_phone}}");
                drawPlaceholder(content, dancingScript, 17, 364,
                        "{{campaign_code}}");
                drawPlaceholder(content, roboto, 13, 262,
                        "{{brand_mark}}");
                drawPlaceholder(content, roboto, 13, 160,
                        "{{access_badge}}");

                drawText(content, roboto, 8, 64, 48,
                        "Generated by SyntheticTextReplacementFixtureGenerator",
                        new Color(117, 126, 135));
            }

            COSArray documentId = new COSArray();
            documentId.add(new COSString("pdfdancer-synthetic-text-replacement"));
            documentId.add(new COSString("pdfdancer-synthetic-text-replacement"));
            document.getDocument().setDocumentID(documentId);
            document.save(output.toFile());
        }
    }

    private static PDFont loadFont(PDDocument document, String fileName) throws IOException {
        return PDType0Font.load(document, FIXTURE_ROOT.resolve(fileName).toFile());
    }

    private static void drawPlaceholder(
            PDPageContentStream content,
            PDFont font,
            float fontSize,
            float y,
            String text) throws IOException {
        content.setNonStrokingColor(new Color(245, 247, 249));
        content.addRect(64, y - 14, 484, 48);
        content.fill();
        content.setStrokingColor(new Color(218, 224, 230));
        content.setLineWidth(0.75f);
        content.addRect(64, y - 14, 484, 48);
        content.stroke();
        drawText(content, font, fontSize, 80, y + 2, text, new Color(30, 45, 61));
    }

    private static void drawText(
            PDPageContentStream content,
            PDFont font,
            float fontSize,
            float x,
            float y,
            String text,
            Color color) throws IOException {
        content.beginText();
        content.setFont(font, fontSize);
        content.setNonStrokingColor(color);
        content.newLineAtOffset(x, y);
        content.showText(text);
        content.endText();
    }
}
